spring:
  application:
    name: gateway
  config:
    import: configserver:http://${CONFIGURATION_HOST:localhost}:${CONFIGURATION_PORT:8888}
    fail-fast: true

server:
  port: ${GATEWAY_PORT:8080}
