spring:
  application:
    name: orders

  config:
    import: configserver:http://${CONFIGURATION_HOST:localhost}:${CONFIGURATION_PORT:8888}
    fail-fast: true
  profiles:
    active: microservice

  kafka:
    service: localhost:9092

app:
  kafka:
    from-tickets-id: "from-tickets"
    from-payments-id: "from-payments"

    tickets-orders-topic: "tickets-to-orders"
    payments-orders-topic: "payments-to-orders"

    orders-tickets-topic: "orders-to-tickets"
    orders-payments-topic: "orders-to-payments"