server:
  port: ${CONFIGURATION_PORT:8888}

spring:
  application:
    name: configuration
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bishop290/landmarks-configs.git
          skipSslValidation: true
          default-label: main
          clone-on-start: true
