spring:
  application:
    name: tickets

  config:
    import: configserver:http://${CONFIGURATION_HOST:localhost}:${CONFIGURATION_PORT:8888}
    fail-fast: true
  profiles:
    active: microservice

  kafka:
    service: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}

app:
  kafka:
    from-orders-id: "from-orders"

    orders-tickets-topic: "orders-to-tickets"
    tickets-orders-topic: "tickets-to-orders"
